name: scipp-docs

channels:
  - conda-forge
  - scipp/label/dev
  - plotly

dependencies:
  - python>=3
  - pip
  - ipython=7.2.0
  - sphinx>=1.6
  - pandoc
  - nbconvert!=5.4
  - ipykernel
  - pip:
    - nbsphinx
  - scipp
  - matplotlib
  - plotly
  - plotly-orca
  - ipywidgets
  - psutil
  - xvfbwrapper
